<?php
$books = [
	'category1' => [
		['id' => 1,  'author' => 'William Shakespeare',                'title' => 'Hamlet',                              'genre' => 'drama'],
		['id' => 2,  'author' => 'Miguel de Cervantes',                'title' => 'Don Quixote',                         'genre' => 'próza'],
		['id' => 3,  'author' => 'Johann Wolfgang von Goethe',        'title' => 'Faust',                               'genre' => 'drama'],
		['id' => 4,  'author' => 'Daniel Defoe',                      'title' => 'Robinson Crusoe',                     'genre' => 'próza'],
		['id' => 5,  'author' => 'Jonathan Swift',                    'title' => 'Gulliverovy cesty',                  'genre' => 'próza'],
		['id' => 6,  'author' => 'Kliment Gottwald',                  'title' => 'Český kníže Václav',                 'genre' => 'poetry'],
		['id' => 7,  'author' => 'František Přemysl Šulc',            'title' => 'Cestopis československého žáka',     'genre' => 'próza'],
		['id' => 8,  'author' => 'Václav Kliment Klicpera',           'title' => 'Hadrián z Římstalů',                 'genre' => 'drama'],
		['id' => 9,  'author' => 'Jean Racine',                       'title' => 'Faidra',                              'genre' => 'drama'],
		['id' => 10, 'author' => 'Ludvig Holberg',                    'title' => 'Ján Křestitel',                       'genre' => 'drama'],
	],
	'category2' => [
		['id' => 11, 'author' => 'Jane Austen',                       'title' => 'Pýcha a předsudek',                   'genre' => 'próza'],
		['id' => 12, 'author' => 'Charlotte Brontë',                  'title' => 'Jane Eyrová',                         'genre' => 'próza'],
		['id' => 13, 'author' => 'Charles Dickens',                   'title' => 'Oliver Twist',                        'genre' => 'próza'],
		['id' => 14, 'author' => 'Gustave Flaubert',                  'title' => 'Paní Bovaryová',                      'genre' => 'próza'],
		['id' => 15, 'author' => 'Victor Hugo',                       'title' => 'Chrám Notre-Dame',                    'genre' => 'próza'],
		['id' => 16, 'author' => 'Alexander Dumas',                   'title' => 'Hrabě Monte Christo',                'genre' => 'próza'],
		['id' => 17, 'author' => 'Honoré de Balzac',                  'title' => 'Otec Goriot',                         'genre' => 'próza'],
		['id' => 18, 'author' => 'Jaroslav Hašek',                    'title' => 'Osudy dobrého vojáka Švejka',         'genre' => 'próza'],
		['id' => 19, 'author' => 'Karel Čapek',                       'title' => 'Krakatit',                            'genre' => 'próza'],
		['id' => 20, 'author' => 'Božena Němcová',                    'title' => 'Babička',                             'genre' => 'próza'],
		['id' => 21, 'author' => 'Smetana',                           'title' => 'Kde domov můj',                       'genre' => 'poetry'],
		['id' => 22, 'author' => 'Petr Bezruč',                       'title' => 'Slezské písně',                       'genre' => 'poetry'],
	],
	'category3' => [
		['id' => 23, 'author' => 'George Orwell',                     'title' => '1984',                                'genre' => 'próza'],
		['id' => 24, 'author' => 'Franz Kafka',                       'title' => 'Proces',                              'genre' => 'próza'],
		['id' => 25, 'author' => 'Albert Camus',                      'title' => 'Cizinec',                             'genre' => 'próza'],
		['id' => 26, 'author' => 'Ernest Hemingway',                  'title' => 'Stařec a moře',                       'genre' => 'próza'],
		['id' => 27, 'author' => 'J.D. Salinger',                     'title' => 'Muž, který chytá v žitě',            'genre' => 'próza'],
		['id' => 28, 'author' => 'William Faulkner',                  'title' => 'Mientras agonizo',                    'genre' => 'próza'],
		['id' => 29, 'author' => 'Ray Bradbury',                      'title' => 'Ilustrovaný muž',                     'genre' => 'próza'],
		['id' => 30, 'author' => 'Samuel Beckett',                    'title' => 'Čekám na Godota',                     'genre' => 'drama'],
		['id' => 31, 'author' => 'Tennessee Williams',                'title' => 'Tramvaj do stanice touha',            'genre' => 'drama'],
		['id' => 32, 'author' => 'Arthur Miller',                     'title' => 'Prodej smrti',                        'genre' => 'drama'],
	],
	'category4' => [
		['id' => 33, 'author' => 'Bohumil Hrabal',                    'title' => 'Příliš hlučná samota',                'genre' => 'próza'],
		['id' => 34, 'author' => 'Milan Kundera',                     'title' => 'Nesnesitelná lehkost bytí',           'genre' => 'próza'],
		['id' => 35, 'author' => 'Václav Havel',                      'title' => 'Audience',                            'genre' => 'drama'],
		['id' => 36, 'author' => 'Ivan Klíma',                        'title' => 'Můj zlatý řemeslo',                   'genre' => 'próza'],
		['id' => 37, 'author' => 'Darina Gabzdilová',                 'title' => 'Nebeské bílé město',                  'genre' => 'próza'],
		['id' => 38, 'author' => 'Vladimír Holan',                    'title' => 'Noc s Hamletem',                     'genre' => 'poetry'],
		['id' => 39, 'author' => 'Miroslav Holub',                    'title' => 'Anděl na kolečkách',                  'genre' => 'poetry'],
		['id' => 40, 'author' => 'Josef Kajetán Tyl',                 'title' => 'Fidlovačka',                          'genre' => 'drama'],
	],
];